// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'fr'

export type Locales =
	| 'fr'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * V​o​u​s​ ​ê​t​e​s​ ​c​o​n​n​e​c​t​é​ ​!​ ​(​i​d​:​ ​{​0​}​)
	 * @param {unknown} 0
	 */
	youAreConnected: RequiredParams<'0'>
	base: {
		status: {
			error: {
				/**
				 * e​r​r​e​u​r
				 */
				'default': string
				/**
				 * E​r​r​e​u​r
				 */
				capitalize: string
			}
			warning: {
				/**
				 * a​t​t​e​n​t​i​o​n
				 */
				'default': string
				/**
				 * A​t​t​e​n​t​i​o​n
				 */
				capitalize: string
			}
			info: {
				/**
				 * i​n​f​o​r​m​a​t​i​o​n
				 */
				'default': string
				/**
				 * I​n​f​o​r​m​a​t​i​o​n
				 */
				capitalize: string
			}
			note: {
				/**
				 * n​o​t​e
				 */
				'default': string
				/**
				 * N​o​t​e
				 */
				capitalize: string
			}
			tip: {
				/**
				 * c​o​n​s​e​i​l
				 */
				'default': string
				/**
				 * C​o​n​s​e​i​l
				 */
				capitalize: string
			}
			success: {
				/**
				 * s​u​c​c​è​s
				 */
				'default': string
				/**
				 * S​u​c​c​è​s
				 */
				capitalize: string
			}
			failure: {
				/**
				 * é​c​h​e​c
				 */
				'default': string
				/**
				 * É​c​h​e​c
				 */
				capitalize: string
			}
			pending: {
				/**
				 * e​n​ ​c​o​u​r​s
				 */
				'default': string
				/**
				 * E​n​ ​c​o​u​r​s
				 */
				capitalize: string
			}
			loading: {
				/**
				 * c​h​a​r​g​e​m​e​n​t
				 */
				'default': string
				/**
				 * C​h​a​r​g​e​m​e​n​t
				 */
				capitalize: string
			}
			empty: {
				/**
				 * v​i​d​e
				 */
				'default': string
				/**
				 * V​i​d​e
				 */
				capitalize: string
			}
		}
		action: {
			back: {
				/**
				 * r​e​t​o​u​r
				 */
				'default': string
				/**
				 * R​e​t​o​u​r
				 */
				capitalize: string
			}
			confirm: {
				/**
				 * c​o​n​f​i​r​m​e​r
				 */
				'default': string
				/**
				 * C​o​n​f​i​r​m​e​r
				 */
				capitalize: string
			}
			next: {
				/**
				 * s​u​i​v​a​n​t
				 */
				'default': string
				/**
				 * S​u​i​v​a​n​t
				 */
				capitalize: string
			}
		}
		currency: {
			/**
			 * {​0​|​f​o​r​m​a​t​C​u​r​r​e​n​c​y​}
			 * @param {unknown} 0
			 */
			amount: RequiredParams<'0|formatCurrency'>
		}
		word: {
			/**
			 * {​0​|​c​a​p​i​t​a​l​i​z​e​}
			 * @param {unknown} 0
			 */
			capitalize: RequiredParams<'0|capitalize'>
		}
	}
	auth: {
		/**
		 * E​m​a​i​l
		 */
		email: string
		/**
		 * N​o​m
		 */
		name: string
		/**
		 * M​o​t​ ​d​e​ ​p​a​s​s​e
		 */
		password: string
		/**
		 * U​n​ ​e​m​a​i​l​ ​d​e​ ​c​o​n​f​i​r​m​a​t​i​o​n​ ​v​o​u​s​ ​a​ ​é​t​é​ ​e​n​v​o​y​é
		 */
		confirmEmail: string
		/**
		 * C​o​n​n​e​x​i​o​n
		 */
		signIn: string
		/**
		 * I​n​s​c​r​i​p​t​i​o​n
		 */
		signUp: string
		/**
		 * C​o​n​n​e​x​i​o​n​ ​p​a​r​ ​l​i​e​n​ ​m​a​g​i​q​u​e
		 */
		signInWithOtp: string
		/**
		 * U​n​ ​l​i​e​n​ ​d​e​ ​c​o​n​n​e​x​i​o​n​ ​a​ ​é​t​é​ ​e​n​v​o​y​é​ ​à​ ​{​e​m​a​i​l​}
		 * @param {unknown} email
		 */
		checkEmail: RequiredParams<'email'>
		/**
		 * P​a​s​ ​e​n​c​o​r​e​ ​d​e​ ​c​o​m​p​t​e​ ​?​ ​C​r​é​e​z​ ​e​n​ ​u​n​ ​!
		 */
		switchToSignup: string
		/**
		 * D​é​j​à​ ​i​n​s​c​r​i​t​ ​?​ ​C​o​n​n​e​c​t​e​z​-​v​o​u​s​ ​!
		 */
		switchToSignin: string
	}
}

export type TranslationFunctions = {
	/**
	 * Vous êtes connecté ! (id: {0})
	 */
	youAreConnected: (arg0: unknown) => LocalizedString
	base: {
		status: {
			error: {
				/**
				 * erreur
				 */
				'default': () => LocalizedString
				/**
				 * Erreur
				 */
				capitalize: () => LocalizedString
			}
			warning: {
				/**
				 * attention
				 */
				'default': () => LocalizedString
				/**
				 * Attention
				 */
				capitalize: () => LocalizedString
			}
			info: {
				/**
				 * information
				 */
				'default': () => LocalizedString
				/**
				 * Information
				 */
				capitalize: () => LocalizedString
			}
			note: {
				/**
				 * note
				 */
				'default': () => LocalizedString
				/**
				 * Note
				 */
				capitalize: () => LocalizedString
			}
			tip: {
				/**
				 * conseil
				 */
				'default': () => LocalizedString
				/**
				 * Conseil
				 */
				capitalize: () => LocalizedString
			}
			success: {
				/**
				 * succès
				 */
				'default': () => LocalizedString
				/**
				 * Succès
				 */
				capitalize: () => LocalizedString
			}
			failure: {
				/**
				 * échec
				 */
				'default': () => LocalizedString
				/**
				 * Échec
				 */
				capitalize: () => LocalizedString
			}
			pending: {
				/**
				 * en cours
				 */
				'default': () => LocalizedString
				/**
				 * En cours
				 */
				capitalize: () => LocalizedString
			}
			loading: {
				/**
				 * chargement
				 */
				'default': () => LocalizedString
				/**
				 * Chargement
				 */
				capitalize: () => LocalizedString
			}
			empty: {
				/**
				 * vide
				 */
				'default': () => LocalizedString
				/**
				 * Vide
				 */
				capitalize: () => LocalizedString
			}
		}
		action: {
			back: {
				/**
				 * retour
				 */
				'default': () => LocalizedString
				/**
				 * Retour
				 */
				capitalize: () => LocalizedString
			}
			confirm: {
				/**
				 * confirmer
				 */
				'default': () => LocalizedString
				/**
				 * Confirmer
				 */
				capitalize: () => LocalizedString
			}
			next: {
				/**
				 * suivant
				 */
				'default': () => LocalizedString
				/**
				 * Suivant
				 */
				capitalize: () => LocalizedString
			}
		}
		currency: {
			/**
			 * {0|formatCurrency}
			 */
			amount: (arg0: unknown) => LocalizedString
		}
		word: {
			/**
			 * {0|capitalize}
			 */
			capitalize: (arg0: unknown) => LocalizedString
		}
	}
	auth: {
		/**
		 * Email
		 */
		email: () => LocalizedString
		/**
		 * Nom
		 */
		name: () => LocalizedString
		/**
		 * Mot de passe
		 */
		password: () => LocalizedString
		/**
		 * Un email de confirmation vous a été envoyé
		 */
		confirmEmail: () => LocalizedString
		/**
		 * Connexion
		 */
		signIn: () => LocalizedString
		/**
		 * Inscription
		 */
		signUp: () => LocalizedString
		/**
		 * Connexion par lien magique
		 */
		signInWithOtp: () => LocalizedString
		/**
		 * Un lien de connexion a été envoyé à {email}
		 */
		checkEmail: (arg: { email: unknown }) => LocalizedString
		/**
		 * Pas encore de compte ? Créez en un !
		 */
		switchToSignup: () => LocalizedString
		/**
		 * Déjà inscrit ? Connectez-vous !
		 */
		switchToSignin: () => LocalizedString
	}
}

export type Formatters = {
	capitalize: (value: unknown) => unknown
	formatCurrency: (value: unknown) => unknown
}
